# Generated by Django 4.0.6 on 2022-07-28 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('user_name', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastName', models.CharField(max_length=45)),
                ('FirstName', models.CharField(max_length=45)),
                ('MiddleName', models.CharField(max_length=45)),
                ('ExtensionName', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='EncounterExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='GIID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Promoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PromotersGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.group')),
                ('PromoterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.promoter')),
            ],
        ),
        migrations.CreateModel(
            name='EncounterDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField()),
                ('Longtitude', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Latitude', models.DecimalField(decimal_places=2, max_digits=10)),
                ('EncounterExitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.encounterexit')),
                ('GenderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.gender')),
                ('PromoterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.promoter')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField()),
                ('Longtitude', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Latitude', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ClaimTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.claimtype')),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
                ('PromoterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.promoter')),
                ('SampleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.sample')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerGIID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDImage', models.CharField(max_length=50)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
                ('GIID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.giid')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.contact')),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgreementID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.agreement')),
                ('CusomterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='GenderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.gender'),
        ),
    ]
