# Generated by Django 4.0.6 on 2022-07-29 07:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customersample_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounterdaily',
            name='DateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='encounterdaily',
            name='EncounterExitID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.encounterexit'),
        ),
        migrations.AlterField(
            model_name='encounterdaily',
            name='GenderID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.gender'),
        ),
        migrations.AlterField(
            model_name='encounterdaily',
            name='Latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='encounterdaily',
            name='Longtitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='encounterdaily',
            name='PromoterID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.promoter'),
        ),
    ]
