from django.urls import include, re_path, path
from user import views

# Agreement Contact, Customer, CustomerAgreement, CustomerContact, CustomerGIID, CustomerSample, EncounterDaily, EncounterExit, Gender, GIID, Promoter, Sample,

urlpatterns = [
    path('<int:pk>/', views.EncounterDailyView.as_view(), name='detailcreate'),
    re_path(r'^agreement$', views.AgreementAPI),
    re_path(r'^agreement/([0-9]+)$', views.AgreementAPI),
    re_path(r'^contact$', views.ContactAPI),
    re_path(r'^contact/([0-9]+)$', views.ContactAPI),
    re_path(r'^customer$', views.CustomerAPI),
    re_path(r'^customer/([0-9]+)$', views.CustomerAPI),
    re_path(r'^customerAgreement$', views.CustomerAgreementAPI),
    re_path(r'^customerAgreement/([0-9]+)$', views.CustomerAgreementAPI),
    re_path(r'^customerContact$', views.CustomerContactAPI),
    re_path(r'^customerContact/([0-9]+)$', views.CustomerContactAPI),
    re_path(r'^customerGIID$', views.CustomerGIIDAPI),
    re_path(r'^customerGIId/([0-9]+)$', views.CustomerGIIDAPI),
    re_path(r'^customerSample$', views.CustomerSampelAPI),
    re_path(r'^customerSample/([0-9]+)$', views.CustomerSampelAPI),
    re_path(r'^encounterDaily$', views.EncounterDailyAPI),
    re_path(r'^encounterDaily/([0-9]+)$', views.EncounterDailyAPI),
    re_path(r'^encounterExit$', views.EncounterExitAPI),
    re_path(r'^encounterExit/([0-9]+)$', views.EncounterExitAPI),
    re_path(r'^gender$', views.GenderAPI),
    re_path(r'^gender/([0-9]+)$', views.GenderAPI),
    re_path(r'^giid$', views.GIIDAPI),
    re_path(r'^giid/([0-9]+)$', views.GIIDAPI),
    re_path(r'^promoter$', views.PromoterAPI),
    re_path(r'^promoter/([0-9]+)$', views.PromoterAPI),
    re_path(r'^sample$', views.SampleAPI),
    re_path(r'^sample/([0-9]+)$', views.SampleAPI),
    re_path(r'^group$', views.GroupAPI),
    re_path(r'^group/([0-9]+)$', views.GroupAPI),
    re_path(r'^promotersgroup$', views.PromotersGroupAPI),
    re_path(r'^promotersgroup/([0-9]+)$', views.PromotersGroupAPI),
    re_path(r'^claimtype$', views.ClaimTypeAPI),
    re_path(r'^claimtype/([0-9]+)$', views.ClaimTypeAPI),
    # re_path('register', views.RegisterView.as_view()),
    re_path('login', views.LoginView.as_view()),
    re_path('getuser', views.GetUserView.as_view()),
    re_path('logout', views.LogoutView.as_view()),
    re_path('totalencounterpergroup',
            views.TotalEncounterPerGroupView.as_view()),

]
